### ISSUE TITLE
Generated json is invalid

### ISSUE THREAD

**Issue by ThisIsAreku** [Herlderlord/csv_to_json#1]
According to json specs, both keys and string values should be enclosed in double quotes.

**Comment by Herlderlord** [comment]
Thanks for your help. I'll correct it. ;)

**Comment by Herlderlord** [comment]
Is that better ?

**Comment by ThisIsAreku** [comment]
Yes :) caf7cbb73e75327f1ccabd9f6af1e691039e268e fix it :+1:

**Comment by ThisIsAreku** [comment]
(Note that integer and boolean are not forced to be in double quotes)
